### ISSUE TITLE
Welcher Hardware Stack wird für Solarrollos benötigt?

### ISSUE THREAD

**Issue by TheRiddler1982** [felixmueller/homebridge-zway-velux#1]
Hi Felix,

hoffe, dass es ok ist, dass ich in Deutsch schreibe.

Ich habe 7 Solar-Rollladen vom Typ SSL MK04 0000S sowie ein Velux KLR 200 Control Pad, was ich jetzt durch die Homebridge mit deinem Plugin in naher Zukunft ablösen will :-) (Als Backup habe ich noch für jeden Rollo eine Fernbedienung). Jetzt wollte ich mich ein bisschen in das Thema einlesen, bin mir aber überhaupt nicht sicher was ich in meinem Fall benötige. Ich habe ja keine 230 V Versorgung, sondern Niedervolt über Solar. Welche (Alternativ)Komponenten benötige ich denn?

Freue mich über jede Hilfe.

Viele Grüße,
Sven

**Comment by TheRiddler1982** [comment]
Was ich bisher rausgefunden habe: Anscheinend brauche ich einen KLF050 für jedes Fenster. Gibt es hier auch andere Hardware, ähnlich wie der KLR200, welches in der Lage ist, mehrere Geräte zu bedienen?

**Comment by felixmueller** [comment]
Hallo Sven,

wie du an Hardware-Stack sehen kannst, handelt es sich bei meinem Setup um eine höchst individuelle Installation. 

Ich habe das Plugin auf GitHub veröffentlicht, um es per NPM auf meinem Raspberry Pi installieren zu können und um es für mich zu dokumentieren. 

Es gibt wahrscheinlich inzwischen einfachere Möglichkeiten, Velux Rollos über HomeKit zu steuern. Mein Ziel war es, den KLF050 irgendwie über Homebridge zu schalten. Dafür habe ich mich dann der Fibaro Relais bedient. 

Mittlerweile gibt es ja z.B. Shellys, die per Firmware direkt HomeKit sprechen. Damit spart man sich den ganzen Z-Way Stack. 

Ich wünsche dir viel Erfolg bei deinem Projekt. 

Viele Grüße
Felix
